const ADD_ITEM = {
  REQUEST: 'items/ADD_ITEMS_REQUEST',
  SUCCESS: 'items/ADD_ITEMS_SUCCESS',
  FAILURE: 'items/ADD_ITEMS_FAILURE',
};

const DELETE_ITEM = {
  REQUEST: 'items/DELETE_ITEMS_REQUEST',
  SUCCESS: 'items/DELETE_ITEMS_SUCCESS',
  FAILURE: 'items/DELETE_ITEMS_FAILURE',
};

const GET_ITEM = {
  REQUEST: 'items/GET_ITEMS_REQUEST',
  SUCCESS: 'items/GET_ITEMS_SUCCESS',
  FAILURE: 'items/GET_ITEMS_FAILURE',
};

const QUERY_ITEMS = {
  REQUEST: 'items/QUERY_ITEMS_REQUEST',
  SUCCESS: 'items/QUERY_ITEMS_SUCCESS',
  FAILURE: 'items/QUERY_ITEMS_FAILURE',
};

const LIST_ITEMS = {
  REQUEST: 'items/LIST_ITEMS_REQUEST',
  SUCCESS: 'items/LIST_ITEMS_SUCCESS',
  FAILURE: 'items/LIST_ITEMS_FAILURE',
};

const UPDATE_ITEM = {
  REQUEST: 'items/UPDATE_ITEMS_REQUEST',
  SUCCESS: 'items/UPDATE_ITEMS_SUCCESS',
  FAILURE: 'items/UPDATE_ITEMS_FAILURE',
};

const SET_FILTER = 'items/SET_FILTER';

export default {
  ADD_ITEM,
  DELETE_ITEM,
  GET_ITEM,
  QUERY_ITEMS,
  LIST_ITEMS,
  UPDATE_ITEM,
  SET_FILTER,
};
